# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

$ErrorActionPreference = 'Stop'

# Author sets these two at the top of the stages section.
$script:TOTAL_STAGES = 0
$script:TOTAL_MINUTES = 0

$script:StageIndex = 0
$script:MinutesElapsed = 0
$script:EnvFile = if ($env:ENV_FILE) { $env:ENV_FILE } else { '.env' }
$script:WrittenEnv = @()
$script:WrittenSecret = @()
$script:Skipped = @()

# _Clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
function _Clear {
  if (-not [Console]::IsOutputRedirected) {
    Clear-Host
  }
}

# Banner "Title" - opening frame: what this wizard does and how long it takes.
function Banner {
  param([string]$Title)
  _Clear
  Write-Host ''
  Write-Host "  $Title" -ForegroundColor Blue
  Write-Host "  $script:TOTAL_STAGES stages, about $script:TOTAL_MINUTES minutes"
  Write-Host '  You drive the browser; this wizard tells you exactly what to do and'
  Write-Host '  captures the values you copy back. Stop any time with Ctrl-C and re-run'
  Write-Host '  later - it remembers values already saved.'
  Pause 'Ready to start?'
}

# Stage "Name" <minutes> - clear the screen, then announce a stage and show
# progress + time remaining.
function Stage {
  param([string]$Name, [int]$Minutes = 0)
  _Clear
  $script:StageIndex++
  $remaining = [Math]::Max(0, $script:TOTAL_MINUTES - $script:MinutesElapsed)
  $script:MinutesElapsed += $Minutes
  Write-Host ''
  Write-Host "  Stage $($script:StageIndex)/$script:TOTAL_STAGES - $Name" -ForegroundColor Blue
  Write-Host "  (about $remaining min left)"
}

# Say "..." - a plain instruction line.
function Say {
  param([string]$Text)
  Write-Host "  $Text"
}

# Step "..." - a numbered-feeling action the human takes in the browser.
function Step {
  param([string]$Text)
  Write-Host "  -> $Text" -ForegroundColor Blue
}

function Note {
  param([string]$Text)
  Write-Host "  $Text" -ForegroundColor DarkGray
}

function Warn {
  param([string]$Text)
  Write-Host "  ! $Text" -ForegroundColor Yellow
}

# Open-Url URL - open in the human's browser on Windows.
function Open-Url {
  param([string]$Url)
  Write-Host "  opening $Url" -ForegroundColor Green
  try {
    Start-Process $Url | Out-Null
  } catch {
    Warn "couldn't open a browser - visit it manually: $Url"
  }
}

# Pause "msg" - wait for the human to confirm they've done the manual part.
function Pause {
  param([string]$Message = 'Press Enter to continue')
  Read-Host "  $Message " | Out-Null
}

# Confirm "question" - y/N gate; returns true on yes.
function Confirm {
  param([string]$Question)
  $reply = Read-Host "  $Question [y/N] "
  return $reply -match '^[Yy]'
}

# Get-ExistingValue KEY - current value of KEY in EnvFile, if any.
function Get-ExistingValue {
  param([string]$Key)
  if (-not (Test-Path -LiteralPath $script:EnvFile -PathType Leaf)) {
    return $null
  }
  $line = Get-Content -LiteralPath $script:EnvFile -Encoding UTF8 |
    Where-Object { $_ -match "^$([regex]::Escape($Key))=" } |
    Select-Object -Last 1
  if (-not $line) {
    return $null
  }
  return $line.Substring($line.IndexOf('=') + 1)
}

# Ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
function Ask {
  param([string]$Key, [string]$Prompt)
  $current = Get-ExistingValue $Key
  if ($null -ne $current -and $current -ne '') {
    Write-Host "  $Prompt [Enter keeps current] " -NoNewline
  } else {
    Write-Host "  $Prompt " -NoNewline
  }
  $input = Read-Host
  if ([string]::IsNullOrWhiteSpace($input) -and $null -ne $current) {
    $input = $current
  }
  Set-Variable -Name $Key -Value $input -Scope 1
}

# Ask-Secret KEY "Prompt" - like Ask, but input is hidden.
function Ask-Secret {
  param([string]$Key, [string]$Prompt)
  $current = Get-ExistingValue $Key
  if ($null -ne $current -and $current -ne '') {
    Write-Host "  $Prompt [Enter keeps current] "
  } else {
    Write-Host "  $Prompt "
  }
  $secure = Read-Host -AsSecureString
  $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    $input = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
  }
  if ([string]::IsNullOrWhiteSpace($input) -and $null -ne $current) {
    $input = $current
  }
  Set-Variable -Name $Key -Value $input -Scope 1
}

# Write-Env KEY VALUE - upsert KEY=VALUE into EnvFile (creates it; replaces
# any existing line). Idempotent.
function Write-Env {
  param([string]$Key, [string]$Value)
  $lines = @()
  if (Test-Path -LiteralPath $script:EnvFile -PathType Leaf) {
    $lines = Get-Content -LiteralPath $script:EnvFile -Encoding UTF8 |
      Where-Object { $_ -notmatch "^$([regex]::Escape($Key))=" }
  }
  $lines += "$Key=$Value"
  $path = Join-Path (Get-Location).Path $script:EnvFile
  [System.IO.File]::WriteAllLines($path, [string[]]$lines)
  $script:WrittenEnv += $Key
  Write-Host "  wrote $Key -> $script:EnvFile" -ForegroundColor Green
}

# Set-Secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
function Set-Secret {
  param([string]$Name, [string]$Value)
  $authOk = $false
  if (Get-Command gh -ErrorAction SilentlyContinue) {
    gh auth status *> $null
    $authOk = ($LASTEXITCODE -eq 0)
  }
  if ($authOk) {
    $Value | gh secret set $Name *> $null
    if ($LASTEXITCODE -eq 0) {
      $script:WrittenSecret += $Name
      Write-Host "  set GitHub secret $Name" -ForegroundColor Green
      return
    }
  }
  $script:Skipped += "GitHub secret $Name (set it manually: gh secret set $Name)"
  Warn "skipped GitHub secret $Name - gh not ready; set it later"
}

# Set-GhVariable NAME VALUE - set a GitHub Actions repo variable (non-secret).
function Set-GhVariable {
  param([string]$Name, [string]$Value)
  $authOk = $false
  if (Get-Command gh -ErrorAction SilentlyContinue) {
    gh auth status *> $null
    $authOk = ($LASTEXITCODE -eq 0)
  }
  if ($authOk) {
    gh variable set $Name --body $Value *> $null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  set GitHub variable $Name" -ForegroundColor Green
      return
    }
  }
  $script:Skipped += "GitHub variable $Name"
  Warn "skipped GitHub variable $Name - gh not ready; set it later"
}

# Finish - clear, then a closing summary of everything configured.
function Finish {
  _Clear
  Write-Host ''
  Write-Host '  Setup complete' -ForegroundColor Green
  if ($script:WrittenEnv.Count -gt 0) {
    Note "wrote $($script:WrittenEnv.Count) value(s) to $script:EnvFile: $($script:WrittenEnv -join ', ')"
  }
  if ($script:WrittenSecret.Count -gt 0) {
    Note "set $($script:WrittenSecret.Count) GitHub secret(s): $($script:WrittenSecret -join ', ')"
  }
  if ($script:Skipped.Count -gt 0) {
    Write-Host ''
    Warn 'still to do by hand:'
    foreach ($item in $script:Skipped) {
      Note "  - $item"
    }
  }
  Write-Host ''
}

# ---------------------------------------------------------------------------
# STAGES - author this section. One Stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ---------------------------------------------------------------------------

$script:TOTAL_STAGES = 1
$script:TOTAL_MINUTES = 5

Banner 'Stripe setup'

# Example stage: replace with your real steps.
Stage 'Stripe - API keys' 5
Say "We'll grab your Stripe test keys and store them for local dev + CI."
Open-Url 'https://dashboard.stripe.com/test/apikeys'
Step "On the API keys page, copy the Publishable key (starts pk_test_)."
Ask STRIPE_PUBLISHABLE_KEY 'Paste the publishable key:'
Step "Click 'Reveal test key' on the Secret key row, then copy it."
Ask-Secret STRIPE_SECRET_KEY 'Paste the secret key:'
Write-Env STRIPE_PUBLISHABLE_KEY $STRIPE_PUBLISHABLE_KEY
Write-Env STRIPE_SECRET_KEY $STRIPE_SECRET_KEY
Set-Secret STRIPE_SECRET_KEY $STRIPE_SECRET_KEY

Finish
